#!/bin/bash

DOTFILES=".vim .vimrc .zshrc .screenrc"

export PATH=/bin:/usr/bin:/usr/local/bin; export PATH
git submodule init
git submodule update
for dotfile in $DOTFILES; do
	if [ ! -e ~/$dotfile ]; then
        echo "~/$dotfile"
		ln -s dotfiles/$dotfile ~/$dotfile
	fi
done

# .gitconfig
if [ ! -e ~/.gitconfig ]; then
    if hostname -f | egrep -q 'a4c\.jp$'; then
        echo "~/.gitconfig"
        ln -s dotfiles/.gitconfig.ca ~/.gitconfig
    fi
fi
