#!/bin/bash

DOTFILES=".vim .vimrc .zshrc .screenrc"

export PATH=/bin:/usr/bin:/usr/local/bin; export PATH
git submodule init
git submodule update
for dotfile in $DOTFILES; do
	if [ ! -e ~/$dotfile ]; then
		ln -s dotfiles/$dotfile ~/$dotfile
	fi
done
